# Dockerfile de production pour le frontend Angular
FROM node:18 AS build
WORKDIR /app
COPY package*.json ./
COPY . .
RUN npm install && npm run build

FROM node:18 AS runtime
WORKDIR /app
RUN npm install -g http-server
COPY --from=build /app/dist/frontend ./dist
EXPOSE 4200
CMD ["http-server", "./dist", "-p", "4200", "--cors"]
